### ISSUE TITLE
Add tui/gui for crawling/results/comparison

### ISSUE THREAD

**Issue by lrstanley** [lrstanley/marill#24]

**Comment by Liamraystanley** [comment]
if running in gui mode, should probably not auto-start. thinking, have a screen where they can click "start", which shows live status information and the like.

As for results, and/or comparison, having a two-column design, with a box overlapping in the top right corner showing key bindings. With mouse support, and scroll ability, this should allow gui to be useful without hindering the ability to easily use the tool.

At this stage, I am not sure if gui should be enabled by default, or not. Regardless, a flag should be used to flip the switch the other way, in the event someone doesn't want a gui. (or is having a bot parse some form of output)
